name: blackbird
dependencies:
  - blas=1.0
  - cudatoolkit=10.2.89
  - intel-openmp
  - keras-applications
  - keras=2.4.*
  - keras-preprocessing=1.1.*
  - numba
  - numpy=1.19.1
  - pandas=1.1.1
  - python=3.7.*
  - requests=2.24.*
  - scipy=1.5.*
  - tensorflow=2.3.0
  - tensorflow-gpu=2.3.0
